config:
  partnerId: 123456
  module: UNIVERSAL_CASE_PROPERTIES_SYNC
  type: UNIVERSAL_CASE_PROPERTIES_SYNC
  configClassName: com.spr.shifu.sla.UniversalCasePropertiesSyncDetails
  syncByCaseId:
    CaseSLAReport:
      report: CaseSLAReport
      deletedDimensionName: DELETED
    CaseProcessingSLAReport:
      report: CaseProcessingSLAReport
      deletedDimensionName: DELETED
  syncByCaseNumber:
    CASE_MACRO_USAGE:
      deletedDimensionName: DELETED
      report: CASE_MACRO_USAGE
_class: com.spr.voice.beans.PartnerLevelConfigBean