name: YAML Change Notifier for Charts

on:
  push:
    branches:
      - main
    paths:
      - 'Charts/**/*.yaml'
      - 'Charts/**/*.yml'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: '3'
      
    # - name: send commiter
    #   run: |
    #       var=$(git log -1 --pretty=format:'%an')
    #       curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
    #         -H "Content-Type: application/json" \
    #         -d "{\"diff\": \"$var\"}"
    # - name: Store changed files
    #   run: |
    #       ls
    #       var=$(git diff --name-only -r HEAD^1 HEAD)
    #       # var=$(git log)
    #       echo $var
    #        curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
    #          -H "Content-Type: application/json" \
    #          -d "{\"diff\": \"$var\"}"
    - name: Send POST requests for modified or added YAML files
      run: |
        # sudo snap install yq
        # sudo cat /etc/myfile | yq '.a.path'
        # for file in $(git diff --name-only --diff-filter=AM HEAD^1 HEAD | grep -E 'Charts/.*\.(yml|yaml)'); do
        #     author_name=$(git log -1 --pretty=format:'%an' -- "$file")
        #     author_email=$(git log -1 --pretty=format:'%ae' -- "$file")
        
        #     # Parse YAML file using a YAML parser
        #     key=$(yq eval '.key' "$file")
        #     property=$(yq eval '.property' "$file")
        #     value=$(yq eval '.value' "$file")
        #     reason=$(yq eval '.reason' "$file")
        #     deleted=$(yq eval '.deleted' "$file")
        
        #     # Construct payload
        #     payload=$(jq -n \
        #         --arg file "$file" \
        #         --arg author_name "$author_name" \
        #         --arg author_email "$author_email" \
        #         --arg key "$key" \
        #         --arg property "$property" \
        #         --arg value "$value" \
        #         --arg reason "$reason" \
        #         --arg deleted "$deleted" \
        #         '{file: $file, author: {name: $author_name, email: $author_email}, key: $key, property: $property, value: $value, reason: $reason, deleted: $deleted}')
        
        #     # Send payload using curl
        #     curl -X POST -H "Content-Type: application/json" -d "$payload" https://8a81-14-194-6-234.ngrok-free.app/webhook/github
        # done
        for file in $(git diff --name-only --diff-filter=AM HEAD^1 HEAD | grep -E 'Charts/.*\.(yml|yaml)'); do
            author_name=$(git log -1 --pretty=format:'%an' -- "$file")
            author_email=$(git log -1 --pretty=format:'%ae' -- "$file")
        
            # Initialize variables
            key=""
            property=""
            value=""
            reason=""
            deleted=""
        
            # Read file line by line
            while IFS= read -r line; do
                # Extract key and value pairs
                key=$(echo "$line" | grep -oP 'key\s*:\s*\K.*')
                property=$(echo "$line" | grep -oP 'property\s*:\s*\K.*')
                value=$(echo "$line" | grep -oP 'value\s*:\s*\K.*')
                reason=$(echo "$line" | grep -oP 'reason\s*:\s*\K.*')
                deleted=$(echo "$line" | grep -oP 'deleted\s*:\s*\K.*')
        
                # Construct payload if all fields are found
                if [ -n "$key" ] && [ -n "$property" ] && [ -n "$value" ] && [ -n "$reason" ] && [ -n "$deleted" ]; then
                    # Construct payload
                    payload=$(jq -n \
                        --arg file "$file" \
                        --arg author_name "$author_name" \
                        --arg author_email "$author_email" \
                        --arg key "$key" \
                        --arg property "$property" \
                        --arg value "$value" \
                        --arg reason "$reason" \
                        --arg deleted "$deleted" \
                        '{file: $file, author: {name: $author_name, email: $author_email}, key: $key, property: $property, value: $value, reason: $reason, deleted: $deleted}')
        
                    # Send payload using curl
                    curl -X POST -H "Content-Type: application/json" -d "$payload" https://8a81-14-194-6-234.ngrok-free.app/webhook/github
        
                    # Reset variables for next iteration
                    key=""
                    property=""
                    value=""
                    reason=""
                    deleted=""
                fi
            done < "$file"
        done

      # run: |
      #   for file in $(git diff --name-only --diff-filter=AM HEAD^1 HEAD | grep -E 'Charts/.*\.(yml|yaml)'); do
      #     author_name=$(git log -1 --pretty=format:'%an' -- "$file")
      #     author_email=$(git log -1 --pretty=format:'%ae' -- "$file")
      #     content=$(cat "$file" | jq -Rs .)
      #     payload=$(jq -n \
      #       --arg file "$file" \
      #       --arg author_name "$author_name" \
      #       --arg author_email "$author_email" \
      #       --arg content "$content" \
      #       '{file: $file, author: {name: $author_name, email: $author_email}, content: $content}')
      #     curl -X POST -H "Content-Type: application/json" -d "$payload" https://8a81-14-194-6-234.ngrok-free.app/webhook/github
      #   done
    # - name: demo
    #   run: |
    #      curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
    #         -H "Content-Type: application/json" \
    #         -d "{\"diff\": \"HELLO\"}"
