name: YAML Change Notifier for Charts

on:
  push:
    branches:
      - main
    paths:
      - 'Charts/**/*.yaml'
      - 'Charts/**/*.yml'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: send commiter
      run: |
          var=$(git log -1 --pretty=format:'%an')
          curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
            -H "Content-Type: application/json" \
            -d "{\"diff\": \"$var\"}"
    - name: Store changed files
      run: |
          var=$(git diff --name-only -r HEAD^1 HEAD)
          curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
            -H "Content-Type: application/json" \
            -d "{\"diff\": \"$var\"}"
          
    - name: demo
      run: |
         curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
            -H "Content-Type: application/json" \
            -d "{\"diff\": \"HELLO\"}"
