name: YAML Change Notifier for Charts

on:
  push:
    branches:
      - main
    paths:
      - 'Charts/**/*.yaml'
      - 'Charts/**/*.yml'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '3'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install yq
      run: pip install yq

    - name: Send POST requests for modified or added YAML files
      run: |
        for file in $(git diff --name-only --diff-filter=AM HEAD^1 HEAD | grep -E 'Charts/.*\.(yml|yaml)'); do
          author_name=$(git log -1 --pretty=format:'%an' -- "$file")
          author_email=$(git log -1 --pretty=format:'%ae' -- "$file")
          
          # Extract fields from the YAML file
          key=$(yq e '.key' "$file")
          property=$(yq e '.property' "$file")
          value=$(yq e '.value' "$file")
          reason=$(yq e '.reason' "$file")
          deleted=$(yq e '.deleted' "$file")

          # Create the payload
          payload=$(jq -n \
            --arg file "$file" \
            --arg author_name "$author_name" \
            --arg author_email "$author_email" \
            --arg key "$key" \
            --arg property "$property" \
            --arg value "$value" \
            --arg reason "$reason" \
            --arg deleted "$deleted" \
            '{file: $file, author: {name: $author_name, email: $author_email}, content: {key: $key, property: $property, value: $value, reason: $reason, deleted: $deleted}}')

          # Send the payload
          curl -X POST -H "Content-Type: application/json" -d "$payload" https://8a81-14-194-6-234.ngrok-free.app/webhook/github
        done

# name: YAML Change Notifier for Charts

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'Charts/**/*.yaml'
#       - 'Charts/**/*.yml'

# jobs:
#   notify:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4
#       with:
#           fetch-depth: '3'
      
#     # - name: send commiter
#     #   run: |
#     #       var=$(git log -1 --pretty=format:'%an')
#     #       curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
#     #         -H "Content-Type: application/json" \
#     #         -d "{\"diff\": \"$var\"}"
#     # - name: Store changed files
#     #   run: |
#     #       ls
#     #       var=$(git diff --name-only -r HEAD^1 HEAD)
#     #       # var=$(git log)
#     #       echo $var
#     #        curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
#     #          -H "Content-Type: application/json" \
#     #          -d "{\"diff\": \"$var\"}"
#     - name: Send POST requests for modified or added YAML files
#       run: |
#         for file in $(git diff --name-only --diff-filter=AM HEAD^1 HEAD | grep -E 'Charts/.*\.(yml|yaml)'); do
#           author_name=$(git log -1 --pretty=format:'%an' -- "$file")
#           author_email=$(git log -1 --pretty=format:'%ae' -- "$file")
#           content=$(cat "$file" | jq -Rs .)
#           payload=$(jq -n \
#             --arg file "$file" \
#             --arg author_name "$author_name" \
#             --arg author_email "$author_email" \
#             --arg content "$content" \
#             '{file: $file, author: {name: $author_name, email: $author_email}, content: $content}')
#           curl -X POST -H "Content-Type: application/json" -d "$payload" https://8a81-14-194-6-234.ngrok-free.app/webhook/github
#         done
#     # - name: demo
#     #   run: |
#     #      curl -X POST https://8a81-14-194-6-234.ngrok-free.app/webhook/github \
#     #         -H "Content-Type: application/json" \
#     #         -d "{\"diff\": \"HELLO\"}"
