name: YAML Change Notifier for Charts

on:
  push:
    branches:
      - main
    paths:
      - 'Charts/**/*.yaml'
      - 'Charts/**/*.yml'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: demo
      run: |
         curl -X POST https://8874-14-194-6-234.ngrok-free.app/webhook/github \
            -H "Content-Type: application/json" \
            -d "{\"diff\": \"HELLO\"}"
    - name: hello
      run: |
          #!/bin/bash
          # Check if there are commits before HEAD
          if [ $(git rev-parse --verify HEAD^ 2>/dev/null) ]; then
              # Store the diff output in a variable
              changes=$(git diff HEAD^ HEAD)
          
              # Iterate over each change
              while IFS= read -r line; do
                  # Process each change and perform a POST request with curl
                  curl -X POST https://8874-14-194-6-234.ngrok-free.app/webhook/github \
                      -H "Content-Type: application/json" \
                      -d "{\"diff\": \"$line\"}"
              done <<< "$changes"
          else
              echo "No parent commit exists before HEAD."
          fi

      # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2
      
    # - name: Send POST requests for modified or added YAML files
    #   run: |
    #     for file in $(git diff --name-only --diff-filter=AM ${{ github.sha }}^..${{ github.sha }} | grep -E 'Charts/.*\.(yml|yaml)'); do
    #       author_name=$(git log -1 --pretty=format:'%an' -- "$file")
    #       author_email=$(git log -1 --pretty=format:'%ae' -- "$file")
    #       content=$(cat "$file" | jq -Rs .)
    #       payload=$(jq -n \
    #         --arg file "$file" \
    #         --arg author_name "$author_name" \
    #         --arg author_email "$author_email" \
    #         --arg content "$content" \
    #         '{file: $file, author: {name: $author_name, email: $author_email}, content: $content}')
    #       curl -X POST -H "Content-Type: application/json" -d "$payload" https://8874-14-194-6-234.ngrok-free.app/webhook/github
    #     done

    # - name: Find changed YAML files
    #   id: find_yaml_files
    #   run: |
    #     # Get the list of changed files
    #     git diff --name-status HEAD~1 HEAD | grep -E 'Charts/.*\.(yml|yaml)' > changed_files.txt
    #     echo "Changed files:"
    #     cat changed_files.txt

    # - name: Send POST requests for each changed file
    #   run: |
    #     while IFS= read -r line; do
    #       status=$(echo "$line" | awk '{print $1}')
    #       file=$(echo "$line" | awk '{print $2}')

    #       if [[ -f "$file" ]]; then
    #         # Get the file content
    #         content=$(cat "$file" | jq -Rs .)

    #         # Get the commit author details
    #         author_name=$(git log -1 --pretty=format:'%an' -- "$file")
    #         author_email=$(git log -1 --pretty=format:'%ae' -- "$file")

    #         # Prepare the JSON payload
    #         payload=$(jq -n \
    #           --arg file "$file" \
    #           --arg status "$status" \
    #           --arg author_name "$author_name" \
    #           --arg author_email "$author_email" \
    #           --arg content "$content" \
    #           '{file: $file, status: $status, author: {name: $author_name, email: $author_email}, content: $content}')

    #         # Send the POST request
    #         curl -X POST \
    #           -H "Content-Type: application/json" \
    #           -d "$payload" \
    #           https://8874-14-194-6-234.ngrok-free.app/webhook/github
    #       fi

    #     done < changed_files.txt
