name: YAML Change Notifier for Charts

on:
  push:
    branches:
      - main  # Specify the branch here
    paths:
      - 'Charts/**/*.yaml'
      - 'Charts/**/*.yml'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find changed YAML files
      id: find_yaml_files
      run: |
        # Get the list of changed files
        git diff --name-status HEAD^ HEAD | grep -E 'Charts/.*\.(yml|yaml)' > changed_files.txt
        echo "Changed files:"
        cat changed_files.txt

    - name: Send POST requests for each changed file
      run: |
        while IFS= read -r line; do
          status=$(echo "$line" | awk '{print $1}')
          file=$(echo "$line" | awk '{print $2}')

          if [[ -f "$file" ]]; then
            # Get the file content
            content=$(cat "$file" | jq -Rs .)

            # Get the commit author details
            author_name=$(git log -1 --pretty=format:'%an' -- "$file")
            author_email=$(git log -1 --pretty=format:'%ae' -- "$file")

            # Prepare the JSON payload
            payload=$(jq -n \
              --arg file "$file" \
              --arg status "$status" \
              --arg author_name "$author_name" \
              --arg author_email "$author_email" \
              --arg content "$content" \
              '{file: $file, status: $status, author: {name: $author_name, email: $author_email}, content: $content}')

            # Send the POST request
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "$payload" \
              https://8874-14-194-6-234.ngrok-free.app/webhook/github
          fi

        done < changed_files.txt
