name: Trigger on YAML file changes

on:
  push:
    paths:
      - 'Charts/**.yaml'

jobs:
  send_post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of changed YAML files
        id: get_files
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^Charts/.*\.yaml$')"

      - name: Iterate over changed files and send POST request
        run: |
          for file in ${{ steps.get_files.outputs.changed_files }}; do
            # Extract author name from git log
            author=$(git log -1 --format='%an' -- "${file}")
            # Send POST request with author name and file contents
            curl -X POST -H "Content-Type: application/json" -d '{"author": "'"$author"'", "file": "'"$file"'", "contents": "'"$(cat $file)"'"}' https://192c-203-110-85-250.ngrok-free.app/api
          done
